In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv('post natal data.csv')
df

,Timestamp,Age,Feeling sad or Tearful,Irritable towards baby & partner,Trouble sleeping at night,Problems concentrating or making decision,Overeating or loss of appetite,Feeling anxious,Feeling of guilt,Problems of bonding with baby,Suicide attempt
0,6/14/2022 20:02,35-40,Yes,Yes,Two or more days a week,Yes,Yes,Yes,No,Yes,Yes
1,6/14/2022 20:03,40-45,Yes,No,No,Yes,Yes,No,Yes,Yes,No
2,6/14/2022 20:04,35-40,Yes,No,Yes,Yes,Yes,Yes,No,Sometimes,No
3,6/14/2022 20:05,35-40,Yes,Yes,Yes,Yes,No,Yes,Maybe,No,No
4,6/14/2022 20:06,40-45,Yes,No,Two or more days a week,Yes,No,Yes,No,Yes,No
...,...,...,...,...,...,...,...,...,...,...,...
1498,6/15/2022 0:35,30-35,Yes,No,Two or more days a week,No,No,Yes,Maybe,Sometimes,No
1499,6/15/2022 0:35,25-30,Sometimes,No,No,Often,No,Yes,Maybe,Yes,No
1500,6/15/2022 0:35,25-30,No,Sometimes,Two or more days a week,No,No,No,Yes,No,Not interested to say
1501,6/15/2022 0:36,25-30,No,Sometimes,Yes,Often,No,Yes,No,No,No
1502,6/15/2022 0:36,45-50,Sometimes,Sometimes,Two or more days a week,No,No,No,Maybe,No,No

In [2]:

epds_mapping = {
    'Yes': 2,                 # Moderate symptom
    'No': 0,                  # No symptom
    'Maybe': 1,               # Mild symptom
    'Sometimes': 1,
    'Two or more days a week': 2  # Example for sleep column
}

symptom_cols = [
    'Feeling sad or Tearful',
    'Irritable towards baby & partner',
    'Trouble sleeping at night',
    'Problems concentrating or making decision',
    'Overeating or loss of appetite',
    'Feeling anxious',
    'Feeling of guilt',
    'Problems of bonding with baby'
]

for col in symptom_cols:
    df[col + '_score'] = df[col].map(epds_mapping)

df['Suicide_attempt_score'] = df['Suicide attempt'].map({'Yes': 3, 'No': 0})
score_cols = [col + '_score' for col in symptom_cols] + ['Suicide_attempt_score']
print("\nConverted numeric scores:")
print(df[score_cols].head(5))

Converted numeric scores:
   Feeling sad or Tearful_score  Irritable towards baby & partner_score  \
0                             2                                     2.0
1                             2                                     0.0
2                             2                                     0.0
3                             2                                     2.0
4                             2                                     0.0

   Trouble sleeping at night_score  \
0                                2
1                                0
2                                2
3                                2
4                                2

   Problems concentrating or making decision_score  \
0                                              2.0
1                                              2.0
2                                              2.0
3                                              2.0
4                                              2.0

   Overeating or loss of appetite_score  Feeling anxious_score  \
0                                   2.0                      2
1                                   2.0                      0
2                                   2.0                      2
3                                   0.0                      2
4                                   0.0                      2

   Feeling of guilt_score  Problems of bonding with baby_score  \
0                     0.0                                    2
1                     2.0                                    2
2                     0.0                                    1
3                     1.0                                    0
4                     0.0                                    2

   Suicide_attempt_score
0                    3.0
1                    0.0
2                    0.0
3                    0.0
4                    0.0

In [3]:
score_cols = [col + '_score' for col in symptom_cols] + ['Suicide_attempt_score']

df['EPDS_Total'] = df[score_cols].sum(axis=1)

df['EPDS_Total_normalized'] = df['EPDS_Total'] * (30 / 27)

df['PPD_Result'] = df['EPDS_Total_normalized'].apply(lambda x: 1 if x >= 10 else 0)

df[['EPDS_Total', 'EPDS_Total_normalized', 'PPD_Result']].head(10)

   EPDS_Total  EPDS_Total_normalized  PPD_Result
0        17.0              18.888889           1
1        10.0              11.111111           1
2        11.0              12.222222           1
3        11.0              12.222222           1
4        10.0              11.111111           1
5        11.0              12.222222           1
6         7.0               7.777778           0
7         8.0               8.888889           0
8         9.0              10.000000           1
9        10.0              11.111111           1

In [4]:
threshold = 10

df['PPD_Result'] = df['EPDS_Total_normalized'].apply(lambda x: 1 if x >= threshold else 0)

df[['EPDS_Total', 'PPD_Result']].head(10)

   EPDS_Total  PPD_Result
0        17.0           1
1        10.0           1
2        11.0           1
3        11.0           1
4        10.0           1
5        11.0           1
6         7.0           0
7         8.0           0
8         9.0           1
9        10.0           1

In [5]:
df.to_csv('PPD_dataset_with_scores.csv', index=False)

In [6]:
dff=pd.read_csv('PPD_dataset_with_scores.csv')
dff

,Timestamp,Age,Feeling sad or Tearful,Irritable towards baby & partner,Trouble sleeping at night,Problems concentrating or making decision,Overeating or loss of appetite,Feeling anxious,Feeling of guilt,Problems of bonding with baby,...,Trouble sleeping at night_score,Problems concentrating or making decision_score,Overeating or loss of appetite_score,Feeling anxious_score,Feeling of guilt_score,Problems of bonding with baby_score,Suicide_attempt_score,EPDS_Total,EPDS_Total_normalized,PPD_Result
0,6/14/2022 20:02,35-40,Yes,Yes,Two or more days a week,Yes,Yes,Yes,No,Yes,...,2,2.0,2.0,2,0.0,2,3.0,17.0,18.888889,1
1,6/14/2022 20:03,40-45,Yes,No,No,Yes,Yes,No,Yes,Yes,...,0,2.0,2.0,0,2.0,2,0.0,10.0,11.111111,1
2,6/14/2022 20:04,35-40,Yes,No,Yes,Yes,Yes,Yes,No,Sometimes,...,2,2.0,2.0,2,0.0,1,0.0,11.0,12.222222,1
3,6/14/2022 20:05,35-40,Yes,Yes,Yes,Yes,No,Yes,Maybe,No,...,2,2.0,0.0,2,1.0,0,0.0,11.0,12.222222,1
4,6/14/2022 20:06,40-45,Yes,No,Two or more days a week,Yes,No,Yes,No,Yes,...,2,2.0,0.0,2,0.0,2,0.0,10.0,11.111111,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1498,6/15/2022 0:35,30-35,Yes,No,Two or more days a week,No,No,Yes,Maybe,Sometimes,...,2,0.0,0.0,2,1.0,1,0.0,8.0,8.888889,0
1499,6/15/2022 0:35,25-30,Sometimes,No,No,Often,No,Yes,Maybe,Yes,...,0,NaN,0.0,2,1.0,2,0.0,6.0,6.666667,0
1500,6/15/2022 0:35,25-30,No,Sometimes,Two or more days a week,No,No,No,Yes,No,...,2,0.0,0.0,0,2.0,0,NaN,5.0,5.555556,0
1501,6/15/2022 0:36,25-30,No,Sometimes,Yes,Often,No,Yes,No,No,...,2,NaN,0.0,2,0.0,0,0.0,5.0,5.555556,0
1502,6/15/2022 0:36,45-50,Sometimes,Sometimes,Two or more days a week,No,No,No,Maybe,No,...,2,0.0,0.0,0,1.0,0,0.0,5.0,5.555556,0